f=open('output.txt','w')
data= input('Enter text to write to file: ')
writing_file=f.write(data + '\n')
print('data successfully written to output.txt.')
f.close()
f=open('output.txt','a')
append_file=f.write(input('Enter additional details to append: '))
print('data successfully appended.')
print('final content of output.txt: ')
f=open('output.txt','r')
reading_file=f.read()
print(reading_file)